hybrisadaptor.h: use QMultiMap
* QMap.values() is deprecated since 5.15
  https://codereview.qt-project.org/c/qt/qtbase/+/282869
* and got removed in qtbase-6:
  https://codereview.qt-project.org/c/qt/qtbase/+/297563

* fixes:
In file included from /OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/hammerhead-webos-linux-gnueabi/sensorfw/0.11.4+gitAUTOINC+6d1cee804b-r0/recipe-sysroot/usr/include/QtCore/qnamespace.h:44,
                 from /OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/hammerhead-webos-linux-gnueabi/sensorfw/0.11.4+gitAUTOINC+6d1cee804b-r0/recipe-sysroot/usr/include/QtCore/qobjectdefs.h:48,
                 from /OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/hammerhead-webos-linux-gnueabi/sensorfw/0.11.4+gitAUTOINC+6d1cee804b-r0/recipe-sysroot/usr/include/QtCore/qobject.h:46,
                 from /OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/hammerhead-webos-linux-gnueabi/sensorfw/0.11.4+gitAUTOINC+6d1cee804b-r0/recipe-sysroot/usr/include/QtCore/QObject:1,
                 from /OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/hammerhead-webos-linux-gnueabi/sensorfw/0.11.4+gitAUTOINC+6d1cee804b-r0/git/core/hybrisadaptor.h:24,
                 from /OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/hammerhead-webos-linux-gnueabi/sensorfw/0.11.4+gitAUTOINC+6d1cee804b-r0/git/core/hybrisadaptor.cpp:21:
/OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/hammerhead-webos-linux-gnueabi/sensorfw/0.11.4+gitAUTOINC+6d1cee804b-r0/git/core/hybrisadaptor.cpp: In member function 'void HybrisManager::processSample(const sensors_event_t&)':
/OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/hammerhead-webos-linux-gnueabi/sensorfw/0.11.4+gitAUTOINC+6d1cee804b-r0/git/core/hybrisadaptor.cpp:701:65: error: no matching function for call to 'QMap<int, HybrisAdaptor*>::values(const int32_t&)'
  701 |     foreach (HybrisAdaptor *adaptor, m_registeredAdaptors.values(data.type)) {
      |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
In file included from /OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/hammerhead-webos-linux-gnueabi/sensorfw/0.11.4+gitAUTOINC+6d1cee804b-r0/recipe-sysroot/usr/include/QtCore/qdebug.h:47,
                 from /OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/hammerhead-webos-linux-gnueabi/sensorfw/0.11.4+gitAUTOINC+6d1cee804b-r0/recipe-sysroot/usr/include/QtCore/QDebug:1,
                 from /OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/hammerhead-webos-linux-gnueabi/sensorfw/0.11.4+gitAUTOINC+6d1cee804b-r0/git/core/logging.h:30,
                 from /OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/hammerhead-webos-linux-gnueabi/sensorfw/0.11.4+gitAUTOINC+6d1cee804b-r0/git/core/deviceadaptor.h:37,
                 from /OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/hammerhead-webos-linux-gnueabi/sensorfw/0.11.4+gitAUTOINC+6d1cee804b-r0/git/core/hybrisadaptor.h:29,
                 from /OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/hammerhead-webos-linux-gnueabi/sensorfw/0.11.4+gitAUTOINC+6d1cee804b-r0/git/core/hybrisadaptor.cpp:21:
/OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/hammerhead-webos-linux-gnueabi/sensorfw/0.11.4+gitAUTOINC+6d1cee804b-r0/recipe-sysroot/usr/include/QtCore/qmap.h:432:14: note: candidate: 'QList<ValueType> QMap<Key, T>::values() const [with Key = int; T = HybrisAdaptor*]'
  432 |     QList<T> values() const
      |              ^~~~~~
/OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/hammerhead-webos-linux-gnueabi/sensorfw/0.11.4+gitAUTOINC+6d1cee804b-r0/recipe-sysroot/usr/include/QtCore/qmap.h:432:14: note:   candidate expects 0 arguments, 1 provided
/OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/hammerhead-webos-linux-gnueabi/sensorfw/0.11.4+gitAUTOINC+6d1cee804b-r0/git/core/hybrisadaptor.cpp: In member function 'void HybrisManager::registerAdaptor(HybrisAdaptor*)':
/OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/hammerhead-webos-linux-gnueabi/sensorfw/0.11.4+gitAUTOINC+6d1cee804b-r0/git/core/hybrisadaptor.cpp:711:30: error: 'class QMap<int, HybrisAdaptor*>' has no member named 'insertMulti'
  711 |         m_registeredAdaptors.insertMulti(adaptor->m_sensorType, adaptor);
      |                              ^~~~~~~~~~~
make[1]: *** [Makefile.hybris:318: hybrisadaptor.o] Error 1

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>